import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.scss";
import { MainLayout } from "@/layouts/MainLayout";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600&family=Roboto:wght@400;500&display=swap"
          rel="stylesheet"
        />
      </Head>
      <MainLayout>
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum nam, odio maiores tempora
          molestias in corporis magnam ex facere. At enim quas maxime veniam odio ad non dolores
          praesentium, quibusdam accusamus? Unde, reiciendis magni beatae quos tempore natus, harum
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit mollitia quaerat beatae, sed
          illo, assumenda voluptatem ipsum voluptas neque eos recusandae natus optio? Expedita
          accusantium officia cumque repudiandae odio veniam? A animi aspernatur fugit adipisci
          libero! Itaque neque nulla esse. Placeat ipsam porro minus magni? Consequuntur iusto
          asperiores placeat autem quia? Maiores ea totam quo fugiat veritatis excepturi odit quod
          qui accusantium? Illum odit tempora, eaque cum minus sapiente corrupti non cupiditate
          atque! Aliquid impedit aspernatur alias mollitia corrupti cum, voluptatibus in, similique
          unde blanditiis voluptate debitis voluptas amet. Sit commodi vero sint officiis obcaecati
          architecto porro aspernatur deserunt hic. Lorem ipsum, dolor sit amet consectetur
          adipisicing elit. Amet enim incidunt rem vero quo quaerat eligendi voluptate blanditiis,
          facilis accusantium ea at maxime delectus fugit eos rerum unde? Exercitationem placeat
          molestias veniam nulla mollitia ut, dolorem officia sint eius atque, adipisci animi harum
          laudantium accusamus vel fuga sapiente voluptatem quidem vitae et aspernatur tempora.
          Fugit, dolor repellat! Reprehenderit nemo impedit facilis, et non modi, ratione ad omnis
          quasi fuga assumenda labore aliquam repellat! Ad beatae harum eius recusandae minus
          reprehenderit pariatur delectus sint fugiat nam alias placeat eaque similique, quaerat
          veritatis hic a, exercitationem iusto earum architecto laborum omnis! Aliquid, optio
          repudiandae. Nemo quaerat omnis earum totam velit debitis facilis iste voluptas, vero
          cumque quibusdam voluptate vel beatae minus corrupti nisi explicabo molestiae delectus ex
          optio eius magnam nostrum, nulla ullam? Beatae deserunt, recusandae placeat temporibus
          illum nesciunt odit inventore hic saepe aliquid aliquam! In sed obcaecati et repellendus
          officia eveniet labore modi rem dolor quas impedit est maiores ex nobis, ut id dolore
          placeat quis quo fugit quaerat maxime. Obcaecati magni harum quas placeat, aliquid
          recusandae quos iusto maxime commodi necessitatibus eius ducimus voluptas, inventore
          eligendi! Inventore ex nostrum aut voluptatem commodi deleniti voluptatibus? Quia tempore
          quibusdam quasi quidem repellendus atque cum esse ipsa vitae, ipsum, dolore maiores
          inventore amet ipsam dolorem quis deleniti nulla. Eveniet doloribus odit accusamus
          voluptas, voluptatem, deserunt minima sed similique suscipit rem, ipsa expedita delectus
          quo dignissimos dolor. Impedit obcaecati in, expedita esse sunt ipsam necessitatibus
          suscipit optio quas minus at asperiores ex minima id quasi totam voluptatem quae
          cupiditate tempora commodi doloribus inventore et nulla. Magni totam eum, placeat
          mollitia, natus incidunt facere enim modi dolorum hic eligendi facilis? Blanditiis nemo
          placeat eveniet beatae modi laboriosam voluptatem sed hic nisi? Sequi sed veritatis
          suscipit blanditiis voluptatibus quibusdam cumque. Aspernatur quae consectetur omnis sunt
          molestiae accusamus incidunt quos accusantium, nobis tempora pariatur cumque labore alias
          nesciunt voluptatibus eveniet voluptas aut impedit harum architecto at quas placeat rem
          commodi. Suscipit illum quidem error cum? Sint eligendi vitae fugiat animi cumque maiores
          dolore, recusandae expedita qui sequi a earum ut. Ab accusamus aperiam architecto, velit
          tempora sed ullam? Explicabo sapiente laboriosam quisquam deserunt culpa magni
          reprehenderit vel veritatis. Dolores ab sunt dolor laborum non illo repudiandae iste
          dolorum praesentium provident quasi amet voluptatum, deserunt omnis sapiente eius tempora
          sit commodi labore! Qui quos dolor culpa asperiores deleniti aspernatur eius perferendis
          corrupti quisquam consequuntur! At, maxime laboriosam reprehenderit debitis doloremque
          porro itaque ipsa veniam architecto error tempora magni iste mollitia quod ex odit
          eligendi culpa repellendus excepturi. Quaerat omnis consectetur provident qui dicta alias
          id praesentium quos ratione tempore veritatis facilis accusantium doloribus porro iure
          magnam iusto, hic in voluptate deserunt incidunt ad? Vero ad esse vitae, veniam autem,
          error recusandae nisi laudantium nulla quam incidunt neque corporis. Est enim dicta,
          molestias explicabo aliquid autem! Natus sit dolores fugit, sapiente laborum quisquam sed
          perspiciatis? Veritatis, quas, accusantium ex placeat officiis, iste cumque facere omnis
          minus non beatae. Nobis labore nemo deleniti voluptate nulla qui maiores praesentium alias
          eaque corrupti laboriosam ratione, sint tenetur cumque itaque exercitationem officia
          veritatis veniam? Sint ex ratione hic. Fuga, laboriosam possimus illo fugiat illum ipsa
          dignissimos aliquid doloribus itaque deserunt, vel quisquam vero quo ex accusantium
          veritatis dolores sunt reprehenderit ad, voluptatum optio? Voluptatem enim quibusdam amet
          rem ea labore vitae atque culpa eum mollitia at maxime nulla facilis fugit, placeat
          necessitatibus voluptatibus illum fuga adipisci excepturi temporibus itaque id?
          Repellendus mollitia vitae beatae nulla perspiciatis ea nam illo doloribus magnam quisquam
          soluta distinctio dolor quam architecto, necessitatibus blanditiis iure ut consequatur.
          Voluptas quisquam ducimus rem impedit, laborum dolorem porro nisi, ut nostrum, excepturi
          eos praesentium! Delectus aut accusantium dolorem earum mollitia reiciendis tempora
          adipisci. Hic ratione maxime odio possimus voluptatibus ullam fuga recusandae tempore sit
          fugiat! Vitae nemo praesentium optio ad culpa aut cumque, beatae animi minus itaque
          assumenda, a, expedita fugit cupiditate sint eaque adipisci! Quam commodi obcaecati
          sapiente quae libero dolorem in, corporis repellendus animi mollitia maiores reiciendis,
          perferendis itaque aliquid unde accusamus. Accusantium nemo nulla aspernatur modi,
          adipisci, in beatae, consequuntur et enim natus officia non eligendi provident doloremque?
          Voluptatibus, officia laudantium. Harum quam deleniti beatae dolore cupiditate? Ut
          voluptate molestias expedita similique repellat error amet deserunt nobis veniam earum
          consequatur animi minus quam, est natus totam? Rerum consequuntur perspiciatis temporibus
          tenetur odio modi. Error et qui neque molestias ab? Aliquam et voluptatem ullam voluptate,
          in modi fuga nobis eos, explicabo iure quia ut, quod accusantium delectus debitis!
          Pariatur quod iste voluptas ullam ratione obcaecati voluptatibus cum tempore, dolorum,
          possimus consectetur rerum nemo illo? Veritatis odio natus tenetur saepe necessitatibus
          repellendus laboriosam, sapiente quasi sunt corrupti assumenda dolorem nisi cum possimus
          aut provident quam ipsum quia? Blanditiis facere temporibus animi nihil inventore ducimus
          voluptatibus odit error vitae reprehenderit voluptas officia placeat quaerat aperiam est,
          illum nobis in! Sunt error ex odit modi recusandae iste quas harum omnis aut ullam
          cupiditate quos magni nulla inventore nesciunt temporibus, laborum rem? Delectus, sapiente
          fugit modi sed soluta et quaerat reprehenderit architecto non corrupti necessitatibus
          iusto provident, corporis obcaecati quisquam doloribus temporibus placeat iure incidunt
          animi! Quas ducimus, nulla perspiciatis exercitationem corrupti nesciunt, dolor facere
          vero cum ab aliquam nobis non commodi veritatis, maiores sunt quaerat quibusdam numquam!
          Harum, corrupti. Eaque natus dignissimos eligendi alias, provident totam quis veniam
          quaerat soluta ex eos dolor repellendus accusamus explicabo possimus doloribus error
          pariatur commodi quia fugit in exercitationem consectetur asperiores nesciunt. Cum, velit
          repudiandae mollitia assumenda ipsam quo quasi, error ad dolor quibusdam harum cupiditate
          voluptatem. Optio qui cumque quidem reiciendis modi. Incidunt, omnis aliquam vero eos ex
          corrupti repudiandae ratione sed quae recusandae, eaque aliquid iste, alias minima sequi
          facere molestias earum doloribus fuga! Eius, saepe dicta sequi cupiditate inventore,
          expedita eum, repellat provident quas officia accusantium vero praesentium. Molestiae vel
          nesciunt eos magnam, enim architecto, laborum, qui culpa ratione repudiandae alias
          doloremque nulla! Animi, natus quasi minus doloremque rem repellendus voluptatum sapiente
          debitis, totam quia laborum tenetur neque, dolorum vel numquam? Exercitationem, inventore
          soluta nostrum voluptatibus ipsa accusantium quidem ex obcaecati quaerat!
        </p>
      </MainLayout>
    </>
  );
}
